version: "3.9"
services:
  web:
    build:
      args:
        - APP_ENV=Development
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:      
      - 8080:8080
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04@sha256:f54a84b8a802afdfa91a954e8ddfcec9973447ce8efec519adf593b54d49bedf"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=yourStrong(!)Password
